# SubjectDB.gd — All Subjects, Branches, Questions & Gym Leaders (Autoload)
extends Node

# ══════════════════════════════════════════════════════════════════════════════
#  SUBJECT / BRANCH CATALOG
# ══════════════════════════════════════════════════════════════════════════════
const SUBJECTS := {
	"math": {
		"name": "Mathematics", "icon": "∑", "color": Color("#2060d0"),
		"desc": "Equations are enemies.\nSolve them to survive!",
		"branches": {
			"algebra":   {"name":"Algebra",   "icon":"x=", "color":Color("#2060d0"), "desc":"Variables & Equations"},
			"geometry":  {"name":"Geometry",  "icon":"△",  "color":Color("#20a060"), "desc":"Shapes & Proofs"},
			"calculus":  {"name":"Calculus",  "icon":"∫",  "color":Color("#a04020"), "desc":"Limits & Derivatives"},
		}
	},
	"languages": {
		"name": "Languages", "icon": "A", "color": Color("#c07010"),
		"desc": "Words shape reality.\nMaster the power of language!",
		"branches": {
			"english":  {"name":"English",  "icon":"En", "color":Color("#c07010"), "desc":"Grammar & Writing"},
			"spanish":  {"name":"Spanish",  "icon":"Es", "color":Color("#c04040"), "desc":"El Español"},
			"french":   {"name":"French",   "icon":"Fr", "color":Color("#4060c0"), "desc":"Le Français"},
		}
	},
	"music": {
		"name": "Music", "icon": "♪", "color": Color("#8020c0"),
		"desc": "Notes are creatures.\nChords are your power!",
		"branches": {
			"theory":      {"name":"Music Theory", "icon":"♩", "color":Color("#8020c0"), "desc":"Staff, Notes & Scales"},
			"composition": {"name":"Composition",  "icon":"🎼","color":Color("#c04090"), "desc":"Chords & Harmony"},
			"history":     {"name":"Music History","icon":"📜","color":Color("#2060a0"), "desc":"Eras & Composers"},
		}
	}
}

# ══════════════════════════════════════════════════════════════════════════════
#  GYM LEADERS — 20 PER BRANCH (we define 3 sample branches fully)
# ══════════════════════════════════════════════════════════════════════════════
func get_gym_leader(subject: String, branch: String, gym_num: int) -> Dictionary:
	var key := subject + ":" + branch
	var leaders = _leaders.get(key, {})
	if leaders.is_empty():
		return _generic_leader(subject, branch, gym_num)
	return leaders.get(gym_num, _generic_leader(subject, branch, gym_num))

func _generic_leader(subject: String, branch: String, gym_num: int) -> Dictionary:
	var act := 1 if gym_num <= 5 else (2 if gym_num <= 12 else 3)
	var diff_name = ["Easy","Easy","Medium","Medium","Hard","Hard","Hard","Expert","Expert","Expert","Expert","Expert","Master","Master","Master","Master","Grandmaster","Grandmaster","Grandmaster","Legend"][gym_num-1]
	var col_map := {"math":Color("#2060d0"),"languages":Color("#c07010"),"music":Color("#8020c0")}
	var col = col_map.get(subject, Color("#606060"))
	var b_data: Dictionary = SUBJECTS.get(subject,{}).get("branches",{}).get(branch,{})
	return {
		"name":       "Gym Leader " + str(gym_num),
		"title":      "Guardian of " + b_data.get("name","Knowledge") + " Gym " + str(gym_num),
		"badge_name": b_data.get("name","") + " Badge " + str(gym_num),
		"gym_number": gym_num, "act": act,
		"xp_reward":  200 + gym_num * 50,
		"color":      col,
		"world":      subject + ":" + branch,
		"intro": ["Gym "+str(gym_num)+" — "+diff_name+" difficulty!",
				  "I am the Guardian of "+b_data.get("name","")+" Gym "+str(gym_num)+".",
				  str(5+min(gym_num,5))+" questions. "+str(min(gym_num/5+2,4))+" lives.\n\nBegin!"],
		"win":  ["★ "+b_data.get("name","")+" Badge "+str(gym_num)+" earned! ★",
				 "You grow stronger."],
		"lose": ["Defeated... Study more!", "Return when ready."],
	}

# ── Full defined leaders for Algebra (representative — others use generic) ────
var _leaders := {
	"math:algebra": {
		1:  {"name":"Prof. Sprout",    "title":"Teacher of Pallet Grove",
			 "badge_name":"Seedling Badge","gym_number":1,"act":1,"xp_reward":200,
			 "color":Color("#60b030"),"world":"math:algebra",
			 "intro":["Welcome, "+GameManager.player_name+"!\nI am Prof. Sprout.","Variables: where algebra begins.","3 questions. Let's go!"],
			 "win":["Seedling Badge is yours!\nYour journey begins!"],"lose":["Practice more!"]},
		2:  {"name":"Prof. Axiom",     "title":"Guardian of Variable Citadel",
			 "badge_name":"Variable Badge","gym_number":2,"act":1,"xp_reward":300,
			 "color":Color("#2060d0"),"world":"math:algebra",
			 "intro":["I am Professor Axiom!\nVariables are my domain.","5 questions. 3 lives. Begin!"],
			 "win":["Variable Badge is yours!"],"lose":["Study variables!"]},
		3:  {"name":"Magistra Lin",    "title":"Master of Equations",
			 "badge_name":"Equation Badge","gym_number":3,"act":1,"xp_reward":350,
			 "color":Color("#10a060"),"world":"math:algebra",
			 "intro":["Linear equations rule here.\nI am Magistra Lin!","5 questions!"],
			 "win":["Equation Badge!"],"lose":["Practice linear equations!"]},
		4:  {"name":"Elder Quadrix",   "title":"Sage of Functions",
			 "badge_name":"Function Badge","gym_number":4,"act":1,"xp_reward":400,
			 "color":Color("#c04020"),"world":"math:algebra",
			 "intro":["Functions reveal the universe.\nI am Elder Quadrix!","6 questions!"],
			 "win":["Function Badge!"],"lose":["Study functions!"]},
		5:  {"name":"Elder Crossway",  "title":"Sage of the Crossroads",
			 "badge_name":"Crossroads Badge","gym_number":5,"act":1,"xp_reward":450,
			 "color":Color("#806020"),"world":"math:algebra",
			 "intro":["ACT 1 FINALE.\nI am Elder Crossway!","Are you ready?\n6 questions!"],
			 "win":["ACT 1 COMPLETE!\nCrossroads Badge!"],"lose":["Train harder!"]},
		6:  {"name":"Prof. Parabola",  "title":"Master of Quadratics",
			 "badge_name":"Quadratic Badge","gym_number":6,"act":2,"xp_reward":500,
			 "color":Color("#902020"),"world":"math:algebra",
			 "intro":["ACT 2 BEGINS.\nQuadratics await. I am Prof. Parabola!","7 questions!"],
			 "win":["Quadratic Badge!"],"lose":["Study quadratics!"]},
		7:  {"name":"Scholar Rex",     "title":"Keeper of Inequalities",
			 "badge_name":"Inequality Badge","gym_number":7,"act":2,"xp_reward":540,
			 "color":Color("#406080"),"world":"math:algebra",
			 "intro":["Inequalities define limits.\n7 questions!"],
			 "win":["Inequality Badge!"],"lose":["Practice inequalities!"]},
		8:  {"name":"Lady Matrix",     "title":"Guardian of Systems",
			 "badge_name":"System Badge","gym_number":8,"act":2,"xp_reward":580,
			 "color":Color("#8040a0"),"world":"math:algebra",
			 "intro":["Systems of equations await.\n7 questions!"],
			 "win":["System Badge!"],"lose":["Study systems!"]},
		9:  {"name":"Dr. Radical",     "title":"Master of Radicals",
			 "badge_name":"Radical Badge","gym_number":9,"act":2,"xp_reward":620,
			 "color":Color("#208060"),"world":"math:algebra",
			 "intro":["Radicals test the bold.\n8 questions!"],
			 "win":["Radical Badge!"],"lose":["Study radicals!"]},
		10: {"name":"Prof. Rational",  "title":"Keeper of Expressions",
			 "badge_name":"Rational Badge","gym_number":10,"act":2,"xp_reward":660,
			 "color":Color("#606020"),"world":"math:algebra",
			 "intro":["Rational expressions ahead.\n8 questions!"],
			 "win":["Rational Badge!"],"lose":["Study rational expressions!"]},
		11: {"name":"Arch-Axiom",      "title":"Master of Polynomials",
			 "badge_name":"Polynomial Badge","gym_number":11,"act":2,"xp_reward":700,
			 "color":Color("#3020c0"),"world":"math:algebra",
			 "intro":["Polynomials are your enemy.\n9 questions!"],
			 "win":["Polynomial Badge!"],"lose":["Study polynomials!"]},
		12: {"name":"Logarithm Lord",  "title":"Sage of Exponentials",
			 "badge_name":"Exponent Badge","gym_number":12,"act":2,"xp_reward":740,
			 "color":Color("#a06010"),"world":"math:algebra",
			 "intro":["ACT 2 FINALE.\nExponentials and logs await!\n10 questions!"],
			 "win":["ACT 2 COMPLETE!\nExponent Badge!"],"lose":["Study logs and exponents!"]},
		13: {"name":"The Archivist",   "title":"Master of Sequences",
			 "badge_name":"Sequence Badge","gym_number":13,"act":3,"xp_reward":780,
			 "color":Color("#706050"),"world":"math:algebra",
			 "intro":["ACT 3 — MASTERY.\nSequences and series await.\n10 questions!"],
			 "win":["Sequence Badge!"],"lose":["Study sequences!"]},
		14: {"name":"Speed Calc",      "title":"Keeper of Time",
			 "badge_name":"Speed Badge","gym_number":14,"act":3,"xp_reward":820,
			 "color":Color("#c03010"),"world":"math:algebra",
			 "intro":["Time pressure! 8 sec/question.\n10 questions!"],
			 "win":["Speed Badge!"],"lose":["Think faster!"]},
		15: {"name":"Matrix Prime",    "title":"Guardian of Mixed Problems",
			 "badge_name":"Mixed Badge","gym_number":15,"act":3,"xp_reward":860,
			 "color":Color("#204080"),"world":"math:algebra",
			 "intro":["Mixed algebra problems.\n10 questions!"],
			 "win":["Mixed Badge!"],"lose":["Study all topics!"]},
		16: {"name":"Proof Master",    "title":"Sage of Proofs",
			 "badge_name":"Proof Badge","gym_number":16,"act":3,"xp_reward":900,
			 "color":Color("#408040"),"world":"math:algebra",
			 "intro":["Algebraic proofs test your mind.\n10 questions!"],
			 "win":["Proof Badge!"],"lose":["Study proofs!"]},
		17: {"name":"Infinity Sage",   "title":"Keeper of Limits",
			 "badge_name":"Limit Badge","gym_number":17,"act":3,"xp_reward":940,
			 "color":Color("#6020a0"),"world":"math:algebra",
			 "intro":["Limits of your knowledge await.\n11 questions!"],
			 "win":["Limit Badge!"],"lose":["Study harder!"]},
		18: {"name":"Strategist Rex",  "title":"Master of Strategy",
			 "badge_name":"Strategy Badge","gym_number":18,"act":3,"xp_reward":980,
			 "color":Color("#405080"),"world":"math:algebra",
			 "intro":["Strategic algebra thinking.\n11 questions!"],
			 "win":["Strategy Badge!"],"lose":["Think strategically!"]},
		19: {"name":"Kaiser Mathus",   "title":"Champion of Kaiser Gate",
			 "badge_name":"Gate Badge","gym_number":19,"act":3,"xp_reward":1020,
			 "color":Color("#c08010"),"world":"math:algebra",
			 "intro":["One badge before Silver Mountain.\nI am Kaiser Mathus!","12 questions!"],
			 "win":["Gate Badge!\nSilver Mountain awaits!"],"lose":["Not yet worthy."]},
		20: {"name":"Maestro Apex",    "title":"The Last Guardian",
			 "badge_name":"Apex Badge","gym_number":20,"act":3,"xp_reward":1100,
			 "color":Color("#2060a0"),"world":"math:algebra",
			 "intro":["GYM 20.\nThe final test before the Oracle.","12 questions. Everything you know."],
			 "win":["APEX BADGE!\nALL 20 GYMS!\nThe Oracle awaits you."],"lose":["So close..."]},
	}
}

# ══════════════════════════════════════════════════════════════════════════════
#  QUESTIONS — Full bank per branch
# ══════════════════════════════════════════════════════════════════════════════
func get_questions(subject: String, branch: String) -> Array:
	var key := subject + ":" + branch
	return _questions.get(key, _questions.get(subject+":generic", []))

func get_gym_questions(subject: String, branch: String, gym_num: int, count: int) -> Array:
	var all_q := get_questions(subject, branch)
	if all_q.is_empty(): return []
	var min_d = max(1, (gym_num - 1) / 5)
	var filtered: Array = all_q.filter(func(q): return int(q.get("difficulty",1)) >= min_d)
	if filtered.size() < count: filtered = all_q.duplicate()
	return AdaptiveAI.adaptive_select(filtered, subject+":"+branch, GameManager.get_level(), count)

var _questions := {
	# ── Math: Algebra ──────────────────────────────────────────────────────────
	"math:algebra": [
		{"topic":"variables","difficulty":1,"q":"What does a VARIABLE represent?",
		 "opts":["A fixed number","A symbol for an unknown","A math operation","An equation type"],
		 "ans":1,"explain":"Variables (x,y,n) represent\nunknown or changing values."},
		{"topic":"variables","difficulty":1,"q":"If  x = 5,  what is  x + 3?",
		 "opts":["5","3","8","15"],"ans":2,"explain":"x + 3 = 5 + 3 = 8"},
		{"topic":"variables","difficulty":1,"q":"Solve:  x + 4 = 9",
		 "opts":["x=4","x=5","x=13","x=2"],"ans":1,"explain":"Subtract 4: x = 9-4 = 5"},
		{"topic":"variables","difficulty":1,"q":"Which is a VARIABLE?",
		 "opts":["7","3.14","y","100"],"ans":2,"explain":"Letters like y,x,z are variables."},
		{"topic":"variables","difficulty":1,"q":"If y=3x and x=4, find y.",
		 "opts":["7","34","12","1"],"ans":2,"explain":"y = 3×4 = 12"},
		{"topic":"variables","difficulty":1,"q":"If x=2, what is 5x?",
		 "opts":["7","10","52","25"],"ans":1,"explain":"5x = 5×2 = 10"},
		{"topic":"variables","difficulty":1,"q":"Solve:  x - 3 = 7",
		 "opts":["x=4","x=10","x=3","x=21"],"ans":1,"explain":"x = 7+3 = 10"},
		{"topic":"linear","difficulty":2,"q":"Solve:  2x = 14",
		 "opts":["x=7","x=12","x=28","x=2"],"ans":0,"explain":"x = 14÷2 = 7"},
		{"topic":"linear","difficulty":2,"q":"Solve:  3x + 1 = 10",
		 "opts":["x=3","x=4","x=9","x=11"],"ans":0,"explain":"3x=9, x=3"},
		{"topic":"linear","difficulty":2,"q":"Solve:  5x - 5 = 20",
		 "opts":["x=3","x=4","x=5","x=25"],"ans":2,"explain":"5x=25, x=5"},
		{"topic":"linear","difficulty":2,"q":"Solve:  x/4 = 3",
		 "opts":["x=7","x=12","x=0.75","x=1"],"ans":1,"explain":"x = 3×4 = 12"},
		{"topic":"linear","difficulty":2,"q":"Slope of y=3x+2 is...",
		 "opts":["2","3","x","0"],"ans":1,"explain":"y=mx+b: slope m=3"},
		{"topic":"linear","difficulty":2,"q":"Solve:  x+8 = 2x-4",
		 "opts":["x=4","x=12","x=6","x=2"],"ans":1,"explain":"-x=-12, x=12"},
		{"topic":"functions","difficulty":3,"q":"If f(x)=2x+1, find f(3).",
		 "opts":["5","6","7","8"],"ans":2,"explain":"f(3)=2(3)+1=7"},
		{"topic":"functions","difficulty":3,"q":"A FUNCTION maps each input to...",
		 "opts":["Zero outputs","Exactly one output","Two outputs","Many outputs"],
		 "ans":1,"explain":"One input → exactly one output."},
		{"topic":"functions","difficulty":3,"q":"If g(x)=x², find g(4).",
		 "opts":["8","12","16","4"],"ans":2,"explain":"g(4)=4²=16"},
		{"topic":"functions","difficulty":3,"q":"DOMAIN of a function is...",
		 "opts":["Output values","The graph","Valid input set","The slope"],
		 "ans":2,"explain":"Domain = all valid input values."},
		{"topic":"quadratic","difficulty":4,"q":"Standard form of quadratic?",
		 "opts":["y=mx+b","ax²+bx+c=0","x=a+b","y=x+c"],"ans":1,
		 "explain":"ax²+bx+c=0 where a≠0."},
		{"topic":"quadratic","difficulty":4,"q":"How many solutions can a quadratic have at most?",
		 "opts":["1","2","3","Infinite"],"ans":1,"explain":"Degree 2 → at most 2 real solutions."},
		{"topic":"quadratic","difficulty":4,"q":"Solve:  x² = 9",
		 "opts":["x=3","x=±3","x=4.5","x=9"],"ans":1,"explain":"x=±√9=±3"},
		{"topic":"quadratic","difficulty":4,"q":"Factor:  x²+5x+6",
		 "opts":["(x+1)(x+6)","(x+2)(x+3)","(x-2)(x-3)","(x+3)(x+3)"],
		 "ans":1,"explain":"(x+2)(x+3)=x²+5x+6 ✓"},
	],
	# ── Languages: English ────────────────────────────────────────────────────
	"languages:english": [
		{"topic":"nouns","difficulty":1,"q":"What is a NOUN?",
		 "opts":["Action word","Describing word","Person/place/thing/idea","Connecting word"],
		 "ans":2,"explain":"Nouns name things."},
		{"topic":"nouns","difficulty":1,"q":"Find the NOUN: 'The brave knight slept.'",
		 "opts":["brave","slept","The","knight"],"ans":3,"explain":"'knight' names a person."},
		{"topic":"nouns","difficulty":1,"q":"A PROPER NOUN is...",
		 "opts":["Any noun","Specific name, capitalised","A plural noun","A verb"],
		 "ans":1,"explain":"Proper nouns: London, Arix, Monday."},
		{"topic":"nouns","difficulty":1,"q":"How many nouns: 'The cat and the dog ran.'",
		 "opts":["1","2","3","0"],"ans":1,"explain":"cat and dog = 2 nouns."},
		{"topic":"nouns","difficulty":1,"q":"Which is ABSTRACT?",
		 "opts":["Table","London","Freedom","River"],"ans":2,"explain":"Abstract = ideas you can't touch."},
		{"topic":"verbs","difficulty":2,"q":"A VERB is a...",
		 "opts":["Describing word","Naming word","Action or state word","Connecting word"],
		 "ans":2,"explain":"Verbs: run, jump, is, seems."},
		{"topic":"verbs","difficulty":2,"q":"Find the VERB: 'She quickly ran home.'",
		 "opts":["She","quickly","ran","home"],"ans":2,"explain":"'ran' is the action."},
		{"topic":"verbs","difficulty":2,"q":"Past tense of 'eat' is...",
		 "opts":["eated","eat","ate","eating"],"ans":2,"explain":"eat → ate (irregular)"},
		{"topic":"verbs","difficulty":2,"q":"Future tense of 'run' is...",
		 "opts":["ran","runs","will run","running"],"ans":2,"explain":"Future = will + base verb."},
		{"topic":"adjectives","difficulty":2,"q":"An ADJECTIVE describes a...",
		 "opts":["Verb","Noun","Adverb","Sentence"],"ans":1,"explain":"Adjectives modify nouns."},
		{"topic":"adjectives","difficulty":2,"q":"Comparative of 'big' is...",
		 "opts":["most big","bigger","biggest","very big"],"ans":1,"explain":"big → bigger → biggest"},
		{"topic":"sentences","difficulty":3,"q":"A complete sentence needs...",
		 "opts":["Only noun","Only verb","Subject AND predicate","Adjective + noun"],
		 "ans":2,"explain":"Subject (who) + predicate (what)."},
		{"topic":"sentences","difficulty":3,"q":"Which is a COMPOUND SENTENCE?",
		 "opts":["She ran.","The dog barked.","He sang and she danced.","Morning."],
		 "ans":2,"explain":"Two clauses joined by conjunction."},
		{"topic":"sentences","difficulty":3,"q":"Passive voice: which sentence?",
		 "opts":["The dog bit the man.","She wrote the letter.",
				 "The letter was written by her.","They ate cake."],
		 "ans":2,"explain":"Passive: subject receives action."},
		{"topic":"advanced","difficulty":4,"q":"A GERUND is...",
		 "opts":["A noun","A verb used as noun","A describing word","A clause"],
		 "ans":1,"explain":"Gerund = verb+-ing as noun. Swimming is fun."},
		{"topic":"advanced","difficulty":4,"q":"An INFINITIVE is...",
		 "opts":["Past verb","'to'+base verb","Noun phrase","Adjective clause"],
		 "ans":1,"explain":"Infinitive = to + verb. (to run)"},
	],
	# ── Music: Theory ─────────────────────────────────────────────────────────
	"music:theory": [
		{"topic":"staff","difficulty":1,"q":"How many lines on a musical staff?",
		 "opts":["3","4","5","6"],"ans":2,"explain":"Standard staff = 5 lines."},
		{"topic":"staff","difficulty":1,"q":"Treble clef marks...",
		 "opts":["Loud notes","Higher note range","Tempo","Key signature"],
		 "ans":1,"explain":"Treble clef = higher notes."},
		{"topic":"staff","difficulty":1,"q":"Spaces on treble staff spell...",
		 "opts":["EGBDF","FACE","ACEG","BDFA"],"ans":1,
		 "explain":"4 spaces = F-A-C-E bottom to top."},
		{"topic":"notes","difficulty":1,"q":"A WHOLE NOTE gets how many beats?",
		 "opts":["1","2","3","4"],"ans":3,"explain":"Whole=4, Half=2, Quarter=1."},
		{"topic":"notes","difficulty":1,"q":"A QUARTER NOTE gets how many beats?",
		 "opts":["1","2","3","4"],"ans":0,"explain":"Quarter note = 1 beat."},
		{"topic":"notes","difficulty":1,"q":"A HALF NOTE gets how many beats?",
		 "opts":["1","2","3","4"],"ans":1,"explain":"Half note = 2 beats."},
		{"topic":"notes","difficulty":2,"q":"A DOTTED HALF NOTE holds...",
		 "opts":["2 beats","3 beats","4 beats","2.5 beats"],"ans":1,"explain":"Dot adds half: 2+1=3."},
		{"topic":"chords","difficulty":2,"q":"A CHORD is...",
		 "opts":["A single note","Two+ notes together","A rest","A clef"],
		 "ans":1,"explain":"Chord = multiple notes played together."},
		{"topic":"chords","difficulty":2,"q":"A MAJOR chord sounds...",
		 "opts":["Sad","Bright and happy","Tense","Silent"],"ans":1,
		 "explain":"Major chords sound bright/happy."},
		{"topic":"chords","difficulty":2,"q":"Notes C-E-G form a...",
		 "opts":["C minor","G major","C major triad","A minor"],
		 "ans":2,"explain":"C-E-G = C major triad."},
		{"topic":"time","difficulty":2,"q":"In 4/4 time, beats per measure?",
		 "opts":["2","3","4","8"],"ans":2,"explain":"Top number = beats per bar."},
		{"topic":"scales","difficulty":3,"q":"A MAJOR SCALE has how many notes?",
		 "opts":["5","6","7","8"],"ans":3,"explain":"Major scale = 8 notes."},
		{"topic":"scales","difficulty":3,"q":"Major scale pattern (W=whole, H=half)?",
		 "opts":["W-W-H-W-W-W-H","W-H-W-W-H-W-W","H-W-W-W-H-W-W","W-W-W-H-W-W-H"],
		 "ans":0,"explain":"Major: W-W-H-W-W-W-H"},
		{"topic":"scales","difficulty":3,"q":"Semitones in an octave?",
		 "opts":["6","8","10","12"],"ans":3,"explain":"12 semitones per octave."},
		{"topic":"scales","difficulty":4,"q":"C major scale notes are...",
		 "opts":["All black keys","C-D-E-F-G-A-B","C-D-Eb-F-G","C-E-G-B-D"],
		 "ans":1,"explain":"C major = all white keys."},
	],
	# ── Languages: Spanish (sample) ───────────────────────────────────────────
	"languages:spanish": [
		{"topic":"basics","difficulty":1,"q":"'Hola' means...",
		 "opts":["Goodbye","Hello","Please","Thank you"],"ans":1,"explain":"Hola = Hello in Spanish."},
		{"topic":"basics","difficulty":1,"q":"'Gracias' means...",
		 "opts":["Please","Goodbye","Thank you","Sorry"],"ans":2,"explain":"Gracias = Thank you."},
		{"topic":"basics","difficulty":1,"q":"'Buenos días' means...",
		 "opts":["Good night","Good morning","Good afternoon","Hello"],
		 "ans":1,"explain":"Buenos días = Good morning."},
		{"topic":"basics","difficulty":1,"q":"'Por favor' means...",
		 "opts":["Thank you","Please","Excuse me","Goodbye"],"ans":1,"explain":"Por favor = Please."},
		{"topic":"basics","difficulty":1,"q":"'Adiós' means...",
		 "opts":["Hello","Sorry","Please","Goodbye"],"ans":3,"explain":"Adiós = Goodbye."},
		{"topic":"verbs","difficulty":2,"q":"'Yo hablo' means...",
		 "opts":["I listen","I speak","You speak","He speaks"],"ans":1,"explain":"Yo=I, hablo=speak (present)."},
		{"topic":"verbs","difficulty":2,"q":"'Tú comes' means...",
		 "opts":["I eat","You eat","He eats","We eat"],"ans":1,"explain":"Tú=you, comes=eat."},
		{"topic":"verbs","difficulty":2,"q":"'Él/ella es' means...",
		 "opts":["I am","You are","He/she is","We are"],"ans":2,"explain":"Él/ella=he/she, es=is."},
		{"topic":"nouns","difficulty":2,"q":"'El libro' means...",
		 "opts":["The table","The book","The house","The car"],"ans":1,"explain":"Libro = book. El = the (masc)."},
		{"topic":"nouns","difficulty":2,"q":"'La casa' means...",
		 "opts":["The book","The table","The house","The door"],"ans":2,"explain":"Casa = house. La = the (fem)."},
		{"topic":"adjectives","difficulty":3,"q":"'Rojo' means...",
		 "opts":["Blue","Green","Red","Yellow"],"ans":2,"explain":"Rojo = Red."},
		{"topic":"adjectives","difficulty":3,"q":"'Grande' means...",
		 "opts":["Small","Big/Large","Fast","Old"],"ans":1,"explain":"Grande = Big/Large."},
		{"topic":"sentences","difficulty":3,"q":"'¿Cómo te llamas?' means...",
		 "opts":["How are you?","Where are you from?","What is your name?","How old are you?"],
		 "ans":2,"explain":"Cómo te llamas = What is your name?"},
		{"topic":"sentences","difficulty":3,"q":"'Tengo hambre' means...",
		 "opts":["I am thirsty","I am hungry","I am tired","I am happy"],
		 "ans":1,"explain":"Tengo hambre = I am hungry."},
		{"topic":"advanced","difficulty":4,"q":"Past tense of 'hablar' (to speak) is...",
		 "opts":["hablo","hablé","hablaré","hablando"],"ans":1,"explain":"Hablé = I spoke (preterite)."},
	],
}
